<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Symbol;

class SymbolSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $symbols = [
            // Crypto Symbols
            [
                'name' => 'Bitcoin',
                'symbol' => 'BTCUSDT',
                'image' => 'https://via.placeholder.com/30x30/F7931A/white?text=B',
                'category' => 'crypto',
                'description' => 'Bitcoin vs USDT trading pair',
                'base_currency' => 'BTC',
                'quote_currency' => 'USDT',
                'tick_size' => 0.01,
                'lot_size' => 0.001,
                'is_margin_trading' => true,
                'max_leverage' => 125,

                'status' => 'active',
                'timezone' => 'UTC',
                'session' => '24/7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ethereum',
                'symbol' => 'ETHUSDT',
                'image' => 'https://via.placeholder.com/30x30/627EEA/white?text=E',
                'category' => 'crypto',
                'description' => 'Ethereum vs USDT trading pair',
                'base_currency' => 'ETH',
                'quote_currency' => 'USDT',
                'tick_size' => 0.01,
                'lot_size' => 0.01,
                'is_margin_trading' => true,
                'max_leverage' => 100,

                'status' => 'active',
                'timezone' => 'UTC',
                'session' => '24/7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Solana',
                'symbol' => 'SOLUSDT',
                'image' => 'https://via.placeholder.com/30x30/9945FF/white?text=S',
                'category' => 'crypto',
                'description' => 'Solana vs USDT trading pair',
                'base_currency' => 'SOL',
                'quote_currency' => 'USDT',
                'tick_size' => 0.001,
                'lot_size' => 0.1,
                'is_margin_trading' => true,
                'max_leverage' => 75,

                'status' => 'active',
                'timezone' => 'UTC',
                'session' => '24/7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cardano',
                'symbol' => 'ADAUSDT',
                'image' => 'https://via.placeholder.com/30x30/0033AD/white?text=A',
                'category' => 'crypto',
                'description' => 'Cardano vs USDT trading pair',
                'base_currency' => 'ADA',
                'quote_currency' => 'USDT',
                'tick_size' => 0.0001,
                'lot_size' => 1,
                'is_margin_trading' => true,
                'max_leverage' => 50,

                'status' => 'active',
                'timezone' => 'UTC',
                'session' => '24/7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Polygon',
                'symbol' => 'MATICUSDT',
                'image' => 'https://via.placeholder.com/30x30/8247E5/white?text=M',
                'category' => 'crypto',
                'description' => 'Polygon vs USDT trading pair',
                'base_currency' => 'MATIC',
                'quote_currency' => 'USDT',
                'tick_size' => 0.0001,
                'lot_size' => 1,
                'is_margin_trading' => true,
                'max_leverage' => 50,

                'status' => 'active',
                'timezone' => 'UTC',
                'session' => '24/7',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // USA Stock Symbols
            [
                'name' => 'Apple Inc.',
                'symbol' => 'AAPL',
                'image' => 'https://via.placeholder.com/30x30/007AFF/white?text=A',
                'category' => 'usa',
                'description' => 'Apple Inc. stock',
                'base_currency' => 'AAPL',
                'quote_currency' => 'USD',
                'tick_size' => 0.01,
                'lot_size' => 1,
                'is_margin_trading' => true,
                'max_leverage' => 5,

                'status' => 'active',
                'timezone' => 'America/New_York',
                'session' => '9:30-16:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Microsoft Corporation',
                'symbol' => 'MSFT',
                'image' => 'https://via.placeholder.com/30x30/00BCF2/white?text=M',
                'category' => 'usa',
                'description' => 'Microsoft Corporation stock',
                'base_currency' => 'MSFT',
                'quote_currency' => 'USD',
                'tick_size' => 0.01,
                'lot_size' => 1,
                'is_margin_trading' => true,
                'max_leverage' => 5,

                'status' => 'active',
                'timezone' => 'America/New_York',
                'session' => '9:30-16:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tesla Inc.',
                'symbol' => 'TSLA',
                'image' => 'https://via.placeholder.com/30x30/CC0000/white?text=T',
                'category' => 'usa',
                'description' => 'Tesla Inc. stock',
                'base_currency' => 'TSLA',
                'quote_currency' => 'USD',
                'tick_size' => 0.01,
                'lot_size' => 1,
                'is_margin_trading' => true,
                'max_leverage' => 5,

                'status' => 'active',
                'timezone' => 'America/New_York',
                'session' => '9:30-16:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Amazon.com Inc.',
                'symbol' => 'AMZN',
                'image' => 'https://via.placeholder.com/30x30/FF9900/white?text=A',
                'category' => 'usa',
                'description' => 'Amazon.com Inc. stock',
                'base_currency' => 'AMZN',
                'quote_currency' => 'USD',
                'tick_size' => 0.01,
                'lot_size' => 1,
                'is_margin_trading' => true,
                'max_leverage' => 5,

                'status' => 'active',
                'timezone' => 'America/New_York',
                'session' => '9:30-16:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Alphabet Inc.',
                'symbol' => 'GOOGL',
                'image' => 'https://via.placeholder.com/30x30/4285F4/white?text=G',
                'category' => 'usa',
                'description' => 'Alphabet Inc. (Google) stock',
                'base_currency' => 'GOOGL',
                'quote_currency' => 'USD',
                'tick_size' => 0.01,
                'lot_size' => 1,
                'is_margin_trading' => true,
                'max_leverage' => 5,

                'status' => 'active',
                'timezone' => 'America/New_York',
                'session' => '9:30-16:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Forex Symbols
            [
                'name' => 'Euro/US Dollar',
                'symbol' => 'EURUSD',
                'image' => 'https://via.placeholder.com/30x30/4CAF50/white?text=E',
                'category' => 'forex',
                'description' => 'Euro vs US Dollar currency pair',
                'base_currency' => 'EUR',
                'quote_currency' => 'USD',
                'tick_size' => 0.00001,
                'lot_size' => 1.00,
                'is_margin_trading' => true,
                'max_leverage' => 100,

                'status' => 'active',
                'timezone' => 'UTC',
                'session' => '24/7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'British Pound/US Dollar',
                'symbol' => 'GBPUSD',
                'image' => 'https://via.placeholder.com/30x30/2196F3/white?text=G',
                'category' => 'forex',
                'description' => 'British Pound vs US Dollar currency pair',
                'base_currency' => 'GBP',
                'quote_currency' => 'USD',
                'tick_size' => 0.00001,
                'lot_size' => 1.00,
                'is_margin_trading' => true,
                'max_leverage' => 100,

                'status' => 'active',
                'timezone' => 'UTC',
                'session' => '24/7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'US Dollar/Japanese Yen',
                'symbol' => 'USDJPY',
                'image' => 'https://via.placeholder.com/30x30/FF9800/white?text=J',
                'category' => 'forex',
                'description' => 'US Dollar vs Japanese Yen currency pair',
                'base_currency' => 'USD',
                'quote_currency' => 'JPY',
                'tick_size' => 0.001,
                'lot_size' => 1.00,
                'is_margin_trading' => true,
                'max_leverage' => 100,

                'status' => 'active',
                'timezone' => 'UTC',
                'session' => '24/7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'US Dollar/Swiss Franc',
                'symbol' => 'USDCHF',
                'image' => 'https://via.placeholder.com/30x30/9C27B0/white?text=S',
                'category' => 'forex',
                'description' => 'US Dollar vs Swiss Franc currency pair',
                'base_currency' => 'USD',
                'quote_currency' => 'CHF',
                'tick_size' => 0.00001,
                'lot_size' => 1.00,
                'is_margin_trading' => true,
                'max_leverage' => 100,

                'status' => 'active',
                'timezone' => 'UTC',
                'session' => '24/7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Australian Dollar/US Dollar',
                'symbol' => 'AUDUSD',
                'image' => 'https://via.placeholder.com/30x30/607D8B/white?text=A',
                'category' => 'forex',
                'description' => 'Australian Dollar vs US Dollar currency pair',
                'base_currency' => 'AUD',
                'quote_currency' => 'USD',
                'tick_size' => 0.00001,
                'lot_size' => 1.00,
                'is_margin_trading' => true,
                'max_leverage' => 100,

                'status' => 'active',
                'timezone' => 'UTC',
                'session' => '24/7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($symbols as $symbol) {
            Symbol::create($symbol);
        }
    }
}