<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Symbol;
class SymbolSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $symbols = [
            [
                'name' => 'BTC',
                'symbol' => 'BTCUSDT',
                'image' => 'btc.png',
                'supported_resolutions' => json_encode(['1', '5', '15', '30', '60', 'D', '2D', '3D', 'M', 'W', '3W', '6M']),
                'has_no_volume' => false,
                'has_intraday' => true,
                'has_daily' => true,
                'has_weekly_and_monthly' => true,
                'pricescale' => 100,
                'minmov' => 1,
                'ticker' => 'BTCUSDT',
                'timezone' => 'Asia/Ho_Chi_Minh',
                'session' => '24x7',
                'min_price' => 82000,
                'max_price' => 84000,
                'min_change' => 1,
                'max_change' => 3,
            ],
            [
                'name' => 'ETH',
                'symbol' => 'ETHUSDT',
                'image' => 'eth.png',
                'supported_resolutions' => json_encode(['1', '5', '15', '30', '60', 'D', '2D', '3D', 'M', 'W', '3W', '6M']),
                'has_no_volume' => false,
                'has_intraday' => true,
                'has_daily' => true,
                'has_weekly_and_monthly' => true,
                'pricescale' => 100,
                'minmov' => 1,
                'ticker' => 'ETHUSDT',
                'timezone' => 'Asia/Ho_Chi_Minh',
                'session' => '24x7',
                'min_price' => 82000,
                'max_price' => 84000,
                'min_change' => 1,
                'max_change' => 3,
            ],
            [
                'name' => 'SOL',
                'symbol' => 'SOLUSDT',
                'image' => 'sol.png',
                'supported_resolutions' => json_encode(['1', '5', '15', '30', '60', 'D', '2D', '3D', 'M', 'W', '3W', '6M']),
                'has_no_volume' => false,
                'has_intraday' => true,
                'has_daily' => true,
                'has_weekly_and_monthly' => true,
                'pricescale' => 100,
                'minmov' => 1,
                'ticker' => 'SOLUSDT',
                'timezone' => 'Asia/Ho_Chi_Minh',
                'session' => '24x7',
                'min_price' => 82000,
                'max_price' => 84000,
                'min_change' => 1,
                'max_change' => 3,
            ],
            [
                'name' => 'XRP',
                'symbol' => 'XRPUSDT',
                'image' => 'xrp.png',
                'supported_resolutions' => json_encode(['1', '5', '15', '30', '60', 'D', '2D', '3D', 'M', 'W', '3W', '6M']),
                'has_no_volume' => false,
                'has_intraday' => true,
                'has_daily' => true,
                'has_weekly_and_monthly' => true,
                'pricescale' => 100,
                'minmov' => 1,
                'ticker' => 'XRPUSDT',
                'timezone' => 'Asia/Ho_Chi_Minh',
                'session' => '24x7',
                'min_price' => 82000,
                'max_price' => 84000,
                'min_change' => 1,
                'max_change' => 3,
            ],
            [
                'name' => 'ADA',
                'symbol' => 'ADAUSDT',
                'image' => 'ada.png',
                'supported_resolutions' => json_encode(['1', '5', '15', '30', '60', 'D', '2D', '3D', 'M', 'W', '3W', '6M']),
                'has_no_volume' => false,
                'has_intraday' => true,
                'has_daily' => true,
                'has_weekly_and_monthly' => true,
                'pricescale' => 100,
                'minmov' => 1,
                'ticker' => 'ADAUSDT',
                'timezone' => 'Asia/Ho_Chi_Minh',
                'session' => '24x7',
                'min_price' => 82000,
                'max_price' => 84000,
                'min_change' => 1,
                'max_change' => 3,
            ],
            [
                'name' => 'DOGE',
                'symbol' => 'DOGEUSDT',
                'image' => 'doge.png',
                'supported_resolutions' => json_encode(['1', '5', '15', '30', '60', 'D', '2D', '3D', 'M', 'W', '3W', '6M']),
                'has_no_volume' => false,
                'has_intraday' => true,
                'has_daily' => true,
                'has_weekly_and_monthly' => true,
                'pricescale' => 100,
                'minmov' => 1,
                'ticker' => 'DOGEUSDT',
                'timezone' => 'Asia/Ho_Chi_Minh',
                'session' => '24x7',
                'min_price' => 82000,
                'max_price' => 84000,
                'min_change' => 1,
                'max_change' => 3,
            ],
            [
                'name' => 'DOT',
                'symbol' => 'DOTUSDT',
                'image' => 'dot.png',
                'supported_resolutions' => json_encode(['1', '5', '15', '30', '60', 'D', '2D', '3D', 'M', 'W', '3W', '6M']),
                'has_no_volume' => false,
                'has_intraday' => true,
                'has_daily' => true,
                'has_weekly_and_monthly' => true,
                'pricescale' => 100,
                'minmov' => 1,
                'ticker' => 'DOTUSDT',
                'timezone' => 'Asia/Ho_Chi_Minh',
                'session' => '24x7',
                'min_price' => 82000,
                'max_price' => 84000,
                'min_change' => 1,
                'max_change' => 3,
            ],
            [
                'name' => 'BNB',
                'symbol' => 'BNBUSDT',
                'image' => 'bnb.png',
                'supported_resolutions' => json_encode(['1', '5', '15', '30', '60', 'D', '2D', '3D', 'M', 'W', '3W', '6M']),
                'has_no_volume' => false,
                'has_intraday' => true,
                'has_daily' => true,
                'has_weekly_and_monthly' => true,
                'pricescale' => 100,
                'minmov' => 1,
                'ticker' => 'BNBUSDT',
                'timezone' => 'Asia/Ho_Chi_Minh',
                'session' => '24x7',
                'min_price' => 82000,
                'max_price' => 84000,
                'min_change' => 1,
                'max_change' => 3,
            ],
            [
                'name' => 'AVAX',
                'symbol' => 'AVAXUSDT',
                'image' => 'avax.png',
                'supported_resolutions' => json_encode(['1', '5', '15', '30', '60', 'D', '2D', '3D', 'M', 'W', '3W', '6M']),
                'has_no_volume' => false,
                'has_intraday' => true,
                'has_daily' => true,
                'has_weekly_and_monthly' => true,
                'pricescale' => 100,
                'minmov' => 1,
                'ticker' => 'AVAXUSDT',
                'timezone' => 'Asia/Ho_Chi_Minh',
                'session' => '24x7',
                'min_price' => 82000,
                'max_price' => 84000,
                'min_change' => 1,
                'max_change' => 3,
            ],
            [
                'name' => 'LTC',
                'symbol' => 'LTCUSDT',
                'image' => 'ltc.png',
                'supported_resolutions' => json_encode(['1', '5', '15', '30', '60', 'D', '2D', '3D', 'M', 'W', '3W', '6M']),
                'has_no_volume' => false,
                'has_intraday' => true,
                'has_daily' => true,
                'has_weekly_and_monthly' => true,
                'pricescale' => 100,
                'minmov' => 1,
                'ticker' => 'LTCUSDT',
                'timezone' => 'Asia/Ho_Chi_Minh',
                'session' => '24x7',
                'min_price' => 82000,
                'max_price' => 84000,
                'min_change' => 1,
                'max_change' => 3,
            ],
            [
                'name' => 'LINK',
                'symbol' => 'LINKUSDT',
                'image' => 'link.png',
                'supported_resolutions' => json_encode(['1', '5', '15', '30', '60', 'D', '2D', '3D', 'M', 'W', '3W', '6M']),
                'has_no_volume' => false,
                'has_intraday' => true,
                'has_daily' => true,
                'has_weekly_and_monthly' => true,
                'pricescale' => 100,
                'minmov' => 1,
                'ticker' => 'LINKUSDT',
                'timezone' => 'Asia/Ho_Chi_Minh',
                'session' => '24x7',
                'min_price' => 82000,
                'max_price' => 84000,
                'min_change' => 1,
                'max_change' => 3,
            ],
        ];
        foreach ($symbols as $symbol) {
            Symbol::create($symbol);
        }
    }
}
